# Generated by Django 3.0.8 on 2020-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('social_name', models.CharField(max_length=255, verbose_name='Nome Social')),
                ('subscription_status', models.CharField(max_length=255, verbose_name='Situação Cadastral')),
                ('stranger_resident', models.CharField(max_length=1, verbose_name='Residente no Exterior')),
                ('resident_country_code', models.CharField(max_length=100, verbose_name='Código País')),
                ('resident_country', models.CharField(max_length=255, verbose_name='Nome do País')),
                ('mother', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nasc')),
                ('birth_country', models.CharField(max_length=3, verbose_name='Cód. País de Nasc.')),
                ('birth_country_code', models.CharField(max_length=255, verbose_name='País de Nasc.')),
                ('birth_province_code', models.CharField(max_length=3, verbose_name='Cód. Estado de Nasc.')),
                ('birth_city', models.CharField(max_length=255, verbose_name='Natural de')),
                ('birth_city_code', models.CharField(max_length=3, verbose_name='Cód. Cidade de Nasc.')),
                ('gender', models.IntegerField(max_length=1, verbose_name='Sexo')),
                ('occupation_origin_code', models.CharField(max_length=50, verbose_name='Cód. da Natureza da Ocupação')),
                ('occupation_origin', models.CharField(max_length=255, verbose_name='Natureza da Ocupação')),
                ('main_occupation_code', models.CharField(max_length=50, verbose_name='Cód. Ocupação Principal')),
                ('main_occupation', models.CharField(max_length=255, verbose_name='Ocupação Principal')),
                ('occupation_current_year', models.CharField(max_length=50, verbose_name='Exercício da Ocupação')),
                ('administrative_unit', models.CharField(max_length=255, verbose_name='Unidade Administrativa')),
                ('administrative_unit_code', models.CharField(max_length=10, verbose_name='Cod. U. Administrativa')),
                ('address_type', models.CharField(max_length=255, verbose_name='Tipo de Logradouro')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=50, verbose_name='Número')),
                ('address_complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('address_neighbor', models.CharField(max_length=255, verbose_name='Bairro')),
                ('address_zip', models.IntegerField(max_length=10, verbose_name='CEP')),
                ('province_code', models.CharField(max_length=2, verbose_name='UF')),
                ('city_code', models.CharField(max_length=10, verbose_name='Código Município')),
                ('city', models.CharField(max_length=255, verbose_name='Município')),
                ('phone_code', models.CharField(max_length=3, verbose_name='DDD')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('death_date', models.CharField(max_length=4, verbose_name='Ano do Óbito')),
                ('stranger', models.CharField(max_length=1, verbose_name='Estrangeiro')),
                ('updated_at', models.DateField(verbose_name='Data de Atualização')),
                ('created_at', models.DateField(verbose_name='Data de Inscrição')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
