# Generated by Django 3.0.8 on 2020-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_zip',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(verbose_name='Sexo'),
        ),
    ]
